[variables]
PATH = "/usr/local/bin:$PATH"

[phases.setup]
# Usamos aptPkgs para garantir que python e pip existam sem conflitos de libstdc++ do Node
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
